name: Deploy Svelte to GitHub Pages

# Trigger the workflow when pushing to the 'main' branch
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the current code from the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Node.js (use the correct version)
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    # Step 3: Create the .env file
    - name: Create .env file
      run: |
        echo VITE_API_URL=${{ secrets.API_URL }} >> .env

    # Step 4: Install dependencies
    - name: Install dependencies
      run: npm install

    # Step 5: Build the Svelte app (output will go into the dist/ folder)
    - name: Build project
      run: npm run build

    # Step 6: Deploy the dist folder to the gh-pages branch
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.TOKEN }}
        publish_dir: ./dist
        publish_branch: gh-pages
